version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    command: --sql-mode=''
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  gong:
    image: reportaongd/gong:latest
    depends_on:
      - db
    volumes:
      - /my/own/datadir:/var/lib/gong/files
    ports:
      - 80:80
      - 443:443
    environment:
      - GONG_DB_HOST=db

  gong-reporte:
    image: reportaongd/gong-reporte:latest
    depends_on:
      - db
      - gong
    volumes:
      - /my/own/datadir:/var/opt/Gong-Reporte
    ports:
      - 8080:8080
    environment:
      - GONG_REPORTE_DB_HOST=db